#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
BACKEND_DIR="$ROOT_DIR/backend"
FRONTEND_DIR="$ROOT_DIR/frontend"
OUTPUT_DIR="${1:-$ROOT_DIR/release}"
[[ "$OUTPUT_DIR" = /* ]] || OUTPUT_DIR="$ROOT_DIR/$OUTPUT_DIR"
GO_CACHE="${GO_CACHE:-$ROOT_DIR/.cache/go-build}"

command -v go >/dev/null 2>&1 || { echo "[package] go not found"; exit 1; }
command -v npm >/dev/null 2>&1 || { echo "[package] npm not found"; exit 1; }

write_release_env() {
  cat >"$1" <<'EOF'
# Release package defaults
PUBLIC_PORT=11946
WEB_ORIGIN=
NODE_ENV=production
PAN_STATIC_DIR=./web

# Auth
PAN_ADMIN_USERNAME=admin
WEB_SESSION_SECRET=change_me_session_secret
# Example generated by:
# htpasswd -nbBC 10 '' 'change-this-password' | cut -d: -f2
AUTH_PASSWORD_HASH_BCRYPT='$2y$10$qvVeaEjEXOJO5ajAU2hxa.syfhsS96nNNlKmDxDWtuCZraAJyxy3q'
# Replace with your real RSA public key when integrating with the app side.
APP_AUTH_LOCAL_PUBLIC_KEY_FILE=./configs/local-public-key.pem

# Storage
PAN_DATA_DIR=./data
# Copy configs/mounts/*.example.json to *.json to enable runtime mounts.
# PAN_MOUNTS=workspace|Workspace|.

# Limits
MAX_UPLOAD_BYTES=104857600
MAX_EDIT_FILE_BYTES=1048576
EOF
}

echo "[package] preparing release directory"
mkdir -p "$OUTPUT_DIR"
rm -rf "$OUTPUT_DIR/backend" "$OUTPUT_DIR/web" "$OUTPUT_DIR/configs" "$OUTPUT_DIR/data" "$OUTPUT_DIR/logs" "$OUTPUT_DIR/run"
rm -f "$OUTPUT_DIR/.env" "$OUTPUT_DIR/.env.example" "$OUTPUT_DIR/.DS_Store" "$OUTPUT_DIR/start.sh" "$OUTPUT_DIR/stop.sh"
mkdir -p "$OUTPUT_DIR/backend" "$OUTPUT_DIR/web" "$OUTPUT_DIR/configs/mounts"

echo "[package] building backend binary"
mkdir -p "$GO_CACHE"
(
  cd "$BACKEND_DIR"
  GOCACHE="$GO_CACHE" go build -o "$OUTPUT_DIR/backend/pan-api" ./cmd/server
)

echo "[package] building frontend dist"
(
  cd "$FRONTEND_DIR"
  npm ci
  npm run build
)

cp -R "$FRONTEND_DIR/dist/." "$OUTPUT_DIR/web/"

if [[ -f "$ROOT_DIR/configs/local-public-key.example.pem" ]]; then
  cp "$ROOT_DIR/configs/local-public-key.example.pem" "$OUTPUT_DIR/configs/local-public-key.example.pem"
  cp "$ROOT_DIR/configs/local-public-key.example.pem" "$OUTPUT_DIR/configs/local-public-key.pem"
fi

if [[ -d "$ROOT_DIR/configs/mounts" ]]; then
  while IFS= read -r config_path; do
    cp "$config_path" "$OUTPUT_DIR/configs/mounts/"
  done < <(find "$ROOT_DIR/configs/mounts" -maxdepth 1 -type f -name '*.example.json' | sort)
fi

write_release_env "$OUTPUT_DIR/.env.example"

cp "$SCRIPT_DIR/start.sh" "$OUTPUT_DIR/start.sh"
cp "$SCRIPT_DIR/stop.sh" "$OUTPUT_DIR/stop.sh"
chmod +x "$OUTPUT_DIR/backend/pan-api" "$OUTPUT_DIR/start.sh" "$OUTPUT_DIR/stop.sh"

echo "[package] done"
echo "[package] backend binary: $OUTPUT_DIR/backend/pan-api"
echo "[package] static assets: $OUTPUT_DIR/web"
echo "[package] env template: $OUTPUT_DIR/.env.example"
echo "[package] start command: $OUTPUT_DIR/start.sh"
